let
    t = #table( {"playlist", "category"}, {
        // alt/exp amb/bso/chill/ost classical electronic folk jazz/funk/lounge/dub mainstream/pop metal rap regional/dk rock/prog z_+
        {"🕉 Psytrance: Full On Progressive Trance 🕉", "electronic"},
        {"10s Metal Classics", "metal"},
        {"1930's-1950's Swing & Jazz", "jazz/funk/lounge/dub"},
        {"2020 BAILE LATINO", "mainstream/pop"},
        {"2020 SALSA PURA", "mainstream/pop"},
        {"8Bit & 16Bit Chiptunes", "electronic"},
        {"acoust&ballads&sg-sw 10s and beyond", "mainstream/pop"},
        {"acoust&ballads&sg-sw/00s", "mainstream/pop"},
        {"Acoustic Covers", "mainstream/pop"},
        {"Afternoon Acoustic", "mainstream/pop"},
        {"aggrotech & harsh electro", "electronic"},
        {"Ambient 1990s", "amb/bso/chill/ost"},
        {"amor", "mainstream/pop"},
        {"autumn / ruduo", "z_+"},
        {"bachata", "mainstream/pop"},
        {"Beatport - Top 100 Progressive House", "electronic"},
        {"Best of Post-Metal", "metal"},
        {"blues rnb soul", "jazz/funk/lounge/dub"},
        {"Brain Food", "electronic"},
        {"Breakout Country", "country"},
        {"Calm Before the Storm", "metal"},
        {"Cena con Guitarras", "z_+"},
        {"Chebra", "z_+"},
        {"Chill Beats 💙 groove, relax", "amb/bso/chill/ost"},
        {"chill or ethereal", "amb/bso/chill/ost"},
        {"christmas", "z_+"},
        {"Classic pieces", "classical"},
        {"classical", "classical"},
        {"cliche death metal", "metal"},
        {"Coding Mode", "electronic"},
        {"comtemporary classical", "classical"},
        {"cooking mainstream", "jazz/funk/lounge/dub"},
        {"Country by the Grace of God", "country"},
        {"Country Coffeehouse", "country"},
        {"Country Gold", "country"},
        {"Country Rocks", "country"},
        {"country", "country"},
        {"Country/Folk", "folk"},
        {"covers mainstream (less rock)", "mainstream/pop"},
        {"covers not mainstream", "z_+"},
        {"covers which are mainstream", "mainstream/pop"},
        {"cristóbal🤘🖤🤖", "z_+"},
        {"Daily Mix 1", "z_+"},
        {"Daily Mix 2", "z_+"},
        {"Daily Mix 3", "z_+"},
        {"Daily Mix 4", "z_+"},
        {"Daily Mix 5", "z_+"},
        {"Daily Mix 6", "z_+"},
        {"Danish Hits ‍", "regional/dk"},
        {"dark ambient and fear", "amb/bso/chill/ost"},
        {"dark ambient unfearful", "amb/bso/chill/ost"},
        {"datathon", "electronic"},
        {"Deep Dive - 00s Metal", "metal"},
        {"Descubrimiento semanal", "z_+"},
        {"disco parties (d/tr)ance", "electronic"},
        {"disco parties (no trance)", "electronic"},
        {"Djazz/Djent/Jazzcore/Fusion/Jazz/Prog/Math/Metal", "rock/prog"},
        {"Djent // Prog // Core", "rock/prog"},
        {"Djent 2022", "metal"},
        {"Djent Instrumental", "metal"},
        {"Djent Workout", "metal"},
        {"DJENTCORE", "metal"},
        {"Djenty", "metal"},
        {"dk lessons", "z_+"},
        {"dk mood", "z_+"},
        {"Downtempo Beats", "amb/bso/chill/ost"},
        {"dream pop", "mainstream/pop"},
        {"Drum and Bass / Jungle / Reggae", "electronic"},
        {"drum and bass", "electronic"},
        {"Dub Reggae", "jazz/funk/lounge/dub"},
        {"Dub SoundSystem", "jazz/funk/lounge/dub"},
        {"DUB TECHNO", "electronic"},
        {"dub", "jazz/funk/lounge/dub"},
        {"EBM, Dark-Electro & Futurepop", "electronic"},
        {"electro swing", "jazz/funk/lounge/dub"},
        {"electro yolo", "electronic"},
        {"elves", "folk"},
        {"En bucle", "z_+"},
        {"Epic & Melodic", "z_+"},
        {"ethereal not mainstream", "amb/bso/chill/ost"},
        {"euforia", "z_+"},
        {"Éxitos que se te han escapado", "z_+"},
        {"experimental", "alt/exp"},
        {"fast bpm", "electronic"},
        {"Favorites backup", "z_+"},
        {"finnish music", "z_+"},
        {"folk metal", "metal"},
        {"folktronic", "folk"},
        {"funk & boogie ⌁funk", "jazz/funk/lounge/dub"},
        {"Fusion Fest", "z_+"},
        {"german music", "z_+"},
        {"Get down saturday night", "z_+"},
        {"glory with lyrics", "amb/bso/chill/ost"},
        {"GOA TRANCE & PSYTRANCE", "electronic"},
        {"Got Djent?", "metal"},
        {"goth", "alt/exp"},
        {"Gothic / Industrial / Mittelalter / EBM / Futurepop / Gothik / Electropop", "electronic"},
        {"groovy boogie", "z_+"},
        {"guitar", "amb/bso/chill/ost"},
        {"halloween", "z_+"},
        {"Hauntology", "amb/bso/chill/ost"},
        {"Heavy Dub", "jazz/funk/lounge/dub"},
        {"holland music", "z_+"},
        {"Hot Country", "country"},
        {"Hyggelig denmark", "z_+"},
        {"Hyperfocus", "amb/bso/chill/ost"},
        {"Igorrr, Diablo Swing Orchestra, Leprous, and more", "alt/exp"},
        {"indie", "alt/exp"},
        {"Industrial | EBM | Darkwave | Dark Electro | Aggrotech | Industrial Techno by DARKLARK", "electronic"},
        {"Industrial Metal / Cybergoth / Aggrotech / EBM", "electronic"},
        {"industrial metal", "metal"},
        {"industrial rock", "rock/prog"},
        {"instrum. prog. rock & jazz", "rock/prog"},
        {"instrumental glory", "amb/bso/chill/ost"},
        {"Instrumental Madness", "z_+"},
        {"instrumentals", "amb/bso/chill/ost"},
        {"It's ALT Good!", "z_+"},
        {"jazz and others", "jazz/funk/lounge/dub"},
        {"Jazz Classics", "jazz/funk/lounge/dub"},
        {"jazz instrumentals", "z_+"},
        {"Jazz Vibes", "jazz/funk/lounge/dub"},
        {"Jurmala", "z_+"},
        {"just covers ( ͡° ͜ʖ ͡° )", "z_+"},
        {"kizomba", "mainstream/pop"},
        {"Las 24 horas", "z_+"},
        {"Las canciones que más escuchaste en 2019", "z_+"},
        {"Las que se escaparon", "z_+"},
        {"Lentos 80 y 90 en inglés (original) ☑️", "amb/bso/chill/ost"},
        {"Leyendas 2019", "metal"},
        {"leyendas del rock", "metal"},
        {"Lithuanian 2021", "z_+"},
        {"Lithuanian Electronica", "z_+"},
        {"lithuanian music", "z_+"},
        {"lofi beats", "amb/bso/chill/ost"},
        {"lofi hip hop music - beats to relax/study to", "amb/bso/chill/ost"},
        {"Los 2010 España", "z_+"},
        {"LotR chronologically", "amb/bso/chill/ost"},
        {"lounge & fussion", "jazz/funk/lounge/dub"},
        {"Lowkey Tech", "z_+"},
        {"LT ballads", "z_+"},
        {"LT favs", "z_+"},
        {"melodic death metal", "metal"},
        {"Menuo Juodaragis 2022", "folk"},
        {"Metal Covers", "z_+"},
        {"metal not mainstream", "metal"},
        {"Mix de S.U.N. Project", "z_+"},
        {"Mix relajante", "z_+"},
        {"navidad iecisa op", "z_+"},
        {"neofolk mainstream", "folk"},
        {"neofolk not mainstream", "folk"},
        {"New Traditions: Country Heroes", "country"},
        {"No voice", "z_+"},
        {"Nochevieja 2017", "z_+"},
        {"nochevieja", "z_+"},
        {"Northern Spirits", "z_+"},
        {"nu metal", "metal"},
        {"other", "alt/exp"},
        {"pakratuškė", "z_+"},
        {"Peaceful Piano", "amb/bso/chill/ost"},
        {"piano", "classical"},
        {"piso", "z_+"},
        {"Polish Lithuanian Empire Folk Metal", "metal"},
        {"pop", "mainstream/pop"},
        {"Porto Kiurasao", "z_+"},
        {"Post Metal", "z_+"},
        {"Post-metal's Best Tracks", "z_+"},
        {"power metal and etc", "metal"},
        {"Power Metal", "metal"},
        {"prima nerea", "z_+"},
        {"Prog Rock", "rock/prog"},
        {"Prog/Math/Metal/Djent", "rock/prog"},
        {"prog/math/metal/djent/jazz", "jazz/funk/lounge/dub"},
        {"Prog/Math/Metal/General bangers", "rock/prog"},
        {"progressive metal", "rock/prog"},
        {"progressive rock", "rock/prog"},
        {"pstfop @ '21-08-10 < 7.10'", "electronic"},
        {"psy tran bass", "electronic"},
        {"psytrance", "electronic"},
        {"Radar de Novedades", "z_+"},
        {"rap", "rap"},
        {"regalos a mi madre (2011-2015)", "z_+"},
        {"reggae", "jazz/funk/lounge/dub"},
        {"Relax en casa", "z_+"},
        {"Residence Red horse", "mainstream/pop"},
        {"Rimworld", "amb/bso/chill/ost"},
        {"RNB Classics", "z_+"},
        {"rock less mainstream", "rock/prog"},
        {"rock", "rock/prog"},
        {"Roko baladės plėšt iš dūšios", "z_+"},
        {"Russian favs", "z_+"},
        {"S&R hits", "z_+"},
        {"sadness", "amb/bso/chill/ost"},
        {"SALSA & BACHATA HITS", "mainstream/pop"},
        {"Salsa Nation", "mainstream/pop"},
        {"salsa", "mainstream/pop"},
        {"SCHLAGER", "z_+"},
        {"shuffle jumstyle tectonic", "z_+"},
        {"Šlageriai", "z_+"},
        {"smooth & instrum. prog. jazz", "jazz/funk/lounge/dub"},
        {"snow", "amb/bso/chill/ost"},
        {"Sonata + Javier", "z_+"},
        {"Songs To Test Headphones With", "z_+"},
        {"Soundtracks", "z_+"},
        {"SPACE - Ambient", "amb/bso/chill/ost"},
        {"spanish music", "z_+"},
        {"storm", "folk"},
        {"Swing Dance", "jazz/funk/lounge/dub"},
        {"swing", "jazz/funk/lounge/dub"},
        {"symphonic metal", "metal"},
        {"Taming scandinavian languages", "z_+"},
        {"Texas Country Now", "country"},
        {"The New Alt", "z_+"},
        {"The Sound of Lithuanian Metal", "z_+"},
        {"timelapse", "z_+"},
        {"to_class_rel_1k [4.01-8.20]", "z_+"},
        {"Top 50: Dinamarca", "z_+"},
        {"tribal", "folk"},
        {"trip-hop", "jazz/funk/lounge/dub"},
        {"Tropicàlia", "z_+"},
        {"Tu cápsula del tiempo", "z_+"},
        {"Tus canciones favoritas en 2020", "z_+"},
        {"Tus canciones favoritas en 2021", "z_+"},
        {"Tus canciones más escuchadas en 2018", "z_+"},
        {"Tus recuerdos de verano", "z_+"},
        {"Una y otra vez", "z_+"},
        {"uplifting bso", "amb/bso/chill/ost"},
        {"uplifting ost", "amb/bso/chill/ost"},
        {"white knight instrumental", "amb/bso/chill/ost"},
        {"Wild Ambience", "z_+"},
        {"Wild Country", "country"},
        {"Women of Experimental", "z_+"},
        {"woods and folk", "folk"},
        {"workout", "z_+"},
        {"Любовь", "z_+"}
    }),
    sortRows = Table.Sort(t,{{"playlist", Order.Ascending}})
in sortRows